moonshot-platform/moonbox-frontend

- src/app/components/community/moontv/moontv.component.scss
Updated the font style of MoonTV section in Community page.
> Fixed the font issue in community

- src/app/components/community/moontv/moontv.component.html
Fixed line style issue in community MoonTV section.
> Updated line style in Community

- src/app/components/community/moonticket/moonticket.component.ts
Replacing from "Moonranker" to "Moonshooter" in MoonTicket.
> Updated the default text of MoonTicket

- src/app/app-routing.module.ts
- src/app/components/community/moonticket/moonticket.component.html
made it work (https://project-moonshot.me/community#ticket )
> fixed #ticket issue

- src/app/components/community/moontv/moontv.component.ts
Updating the Youtube Video src
> Updated the Video src

- src/app/components/community/moontv/moontv.component.html
Updated youtube video player size
> Updated youtube video player size

- src/app/components/about/about.component.ts
- src/app/components/community/community.component.ts
- src/app/components/landing/landing.component.ts
- src/index.html
Tried to fix Share link for whatsapp
(I could not test in locally.)
> trying to fix meta image issue for whatsapp

- src/app/components/landing/investment/investment.component.html
- src/app/components/landing/investment/investment.component.scss
> Updated Moonbase section

- package-lock.json
- package.json
- src/app/components/base/navigation/navigation.component.html
- src/app/components/base/navigation/navigation.component.scss
- src/app/components/base/navigation/navigation.component.ts
onHover feature is working on desktop-web.
onClick feature is compatible with mobile and tablet
> added on hover and onClick to navbar

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/components/lptoken/intro/intro.component.html
- src/app/components/lptoken/intro/intro.component.scss
- src/app/components/lptoken/intro/intro.component.spec.ts
- src/app/components/lptoken/intro/intro.component.ts
- src/app/components/lptoken/lptoken.component.html
- src/app/components/lptoken/lptoken.component.scss
- src/app/components/lptoken/lptoken.component.spec.ts
- src/app/components/lptoken/lptoken.component.ts
- src/app/components/lptoken/lptoken.module.ts
- src/app/components/lptoken/moonlp/moonlp.component.html
- src/app/components/lptoken/moonlp/moonlp.component.scss
- src/app/components/lptoken/moonlp/moonlp.component.spec.ts
- src/app/components/lptoken/moonlp/moonlp.component.ts
> Clover update

- src/app/components/about/roadmap/roadmap.component.ts
- src/app/components/landing/tutorial/tutorial.component.html
Added Latoken button in Landing page
Changed Latoken item "ongoing" to "done" on Roadmap
> Landing updates

- src/app/components/base/moonbase-bar/moonbase-bar.component.html
- src/app/components/base/moonbase-bar/moonbase-bar.component.scss
- src/app/components/base/moonbase-bar/moonbase-bar.component.spec.ts
- src/app/components/base/moonbase-bar/moonbase-bar.component.ts
- src/app/components/base/sidebar/sidebar.component.html
- src/app/components/base/sidebar/sidebar.component.scss
- src/app/components/base/sidebar/sidebar.component.ts
- src/app/components/base/sidebar/sidebar.module.ts
- src/app/components/base/tokenomics/tokenomics.component.scss
- src/app/services/moonbase.service.ts
Added Moonbase-bar template and Fixed bar closing issue
> Moonbase bar

- src/app/components/base/footer/footer.component.html
- src/app/components/base/navigation/navigation.component.html
- src/app/components/base/sidebar/sidebar.component.ts
The bug was about the clicking the outside of the bar. I added exception for tokenomics <p> tags. Then solved :P
> Fixed Tokenomics Bar issue

- src/app/app.module.ts
- src/app/components/about/about.component.html
- src/app/components/about/about.module.ts
- src/app/components/base/footer-mobile/footer-mobile.component.html
- src/app/components/base/footer-mobile/footer-mobile.component.scss
- src/app/components/base/footer-mobile/footer-mobile.component.spec.ts
- src/app/components/base/footer-mobile/footer-mobile.component.ts
- src/app/components/base/footer-mobile/footer-mobile.module.ts
- src/app/components/base/moonbase-bar/moonbase-bar.component.html
- src/app/components/base/moonbase-bar/moonbase-bar.component.scss
- src/app/components/base/sidebar/sidebar.component.html
- src/app/components/base/sidebar/sidebar.component.ts
- src/app/components/base/tokenomics/tokenomics.component.scss
- src/app/components/community/community.component.html
- src/app/components/community/community.module.ts
- src/app/components/landing/landing.component.html
- src/app/components/landing/landing.component.scss
- src/app/components/landing/landing.module.ts
- src/assets/media/icons/close_bottom-menu_mobile.svg
- Updated bar text
- Removed Scroll bar
> Moonbase bar update

- src/app/components/base/footer-mobile/footer-mobile.component.html
- src/app/components/base/footer-mobile/footer-mobile.component.ts
- src/app/components/base/moonbase-bar/moonbase-bar.component.html
- src/app/components/base/moonbase-bar/moonbase-bar.component.scss
- src/app/components/base/sidebar/sidebar.component.html
- src/app/components/base/sidebar/sidebar.component.scss
- src/app/components/base/tokenomics/tokenomics.component.scss
- src/assets/media/icons/close_bottom-menu_mobile.svg
Updated moonbase side bar layout
> Moonbase bar mobile

- src/app/components/about/about.component.ts
- src/app/components/community/community.component.ts
- src/app/components/landing/landing.component.ts
- src/app/components/token-lock/token-lock.component.ts
- src/index.html
> Seo updates

- src/app/components/base/navigation/navigation.component.ts
- src/app/components/landing/press/press.component.html
- src/app/components/landing/press/press.component.scss
+ Added "Go to MoonNews" button to press section
+ Added "MoonNews" item to navigation bar
> Goto news button

- src/app/components/base/footer-mobile/footer-mobile.component.html
- src/app/components/base/sidebar/sidebar.component.html
Changed sidebar and mobile menu MoonBase text to MoonBoxes
> Changed sidebar and mobile menu MoonBase text to MoonBoxes

- src/app/components/moonticket-promo/moonticket-promo.component.ts
Fixed the moonticket-promo cutting of the year issue
> Tried to fix moonticket-promo cutting of the year issue

- src/app/components/community/moontv/moontv.component.ts
Updated broken moontv video link
> Moontv video updates
